### ISSUE TITLE
'Loader' object has no attribute 'pipeline'

### ISSUE THREAD

**Issue by spwgh** [Zuellni/ComfyUI-PickScore-Nodes#6]
Hello!

Your node seems quite helpful but I'm having issues running it in a recently created ComfyUI installation. I'm using your example workflow with no changes whatsoever. Not sure what's going on, so any help would be appreciated. Seems cool to be able to score images. Here is the stack trace:

## Stack Trace
`!!! Exception during processing !!! 'Loader' object has no attribute 'pipeline'
Traceback (most recent call last):
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI-PickScore-Nodes\pickscore.py", line 118, in select
    model.load()
  File "G:\StableDiffusion\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI-PickScore-Nodes\pickscore.py", line 41, in load
    self.pipeline.to(self.device)
    ^^^^^^^^^^^^^
AttributeError: 'Loader' object has no attribute 'pipeline'`

## System Information
- **ComfyUI Version:** v0.2.2-6-gbb52934
- **Arguments:** ComfyUI\main.py --windows-standalone-build --output-directory D:\ComfyOut
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589410304
  - **VRAM Free:** 7452073888
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 32350112

**Comment by Zuellni** [comment]
Try updating the repo, it should work now.

**Comment by spwgh** [comment]
Working now! Thank you!

**Comment by spwgh** [comment]
Completed.
